# Generated by Django 3.0.8 on 2020-07-25 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boletim', '0002_auto_20200725_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('materias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletim.MateriasSeries')),
            ],
        ),
    ]
