# Generated by Django 3.0.8 on 2020-07-25 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletim', '0004_materias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Materias',
        ),
    ]
